# Welcome to Jekyll!
# 이 파일은 블로그 전체에 영향을 주는 설정을 담고 있어요.
# 자주 수정할 필요는 없고, 자주 바뀌는 데이터는 Jekyll 데이터 파일을 활용하세요.

# 서버 실행 중 수정 시 재시작 필요
# 'bundle exec jekyll serve'를 사용할 때 이 파일은 자동으로 새로고침되지 않아요.

# YAML 문법 참고:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# 사이트 설정
title: EURO-ZONE
email: eurobae@example.com  # 당신의 이메일로 변경하세요
description: >- 
  EURO-ZONE에서 프로젝트, 공부, 코딩 기록을 공유합니다. 알고리즘, 이산수학, 컴공 기초부터 코딩 테스트까지!
baseurl: ""  # GitHub Pages 루트로 사용할 거면 빈칸 유지
url: "https://eurobin39.github.io"  # GitHub Pages URL
github_username: eurobin39  # 당신의 GitHub 사용자 이름
twitter_username:  # 트위터 계정이 있다면 추가

# 카테고리 설정
categories:
  - projects
  - study
  - coding

# 상단 메뉴 설정
header_pages:
  - projects.md
  - study.md
  - coding.md

# 빌드 설정
theme: minima  # 기본 테마 유지, 원하면 다른 테마로 변경 가능
plugins:
  - jekyll-feed  # 피드 생성 플러그인

# 제외 항목
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/